runtime: python37

service: default

entrypoint: gunicorn src/imputationflask:app -b :$PORT

# URL handlers
handlers:
  # Static files
- url: /static
  static_dir: imputationflask/static

  # Direct to main app
- url: /.*
  script: auto


