runtime: python37

service: default

entrypoint: gunicorn app:app -b :$PORT

# URL handlers
handlers:
  # Static files
- url: /static
  static_dir: app/static

  # Direct to main app
- url: /.*
  script: auto


